export type LetterType = "vowel" | "consonant" | "special";

export interface Letter {
	upper: string;
	lower: string;
	sound: string;
	romanized: string;
	exampleWord: string;
	exampleMeaning: string;
	examplePronounced: string;
	type: LetterType;
	tip?: string;
}

export const stats = [
	{ label: "Letters total", value: "29" },
	{ label: "Vowels", value: "8" },
	{ label: "Consonants", value: "21" },
];

export const alphabet: Letter[] = [
	{
		upper: "A",
		lower: "a",
		sound: "a",
		romanized: "a",
		exampleWord: "Araba",
		exampleMeaning: "Car",
		examplePronounced: "ah-RAH-bah",
		type: "vowel",
		tip: "Like 'a' in 'father'.",
	},
	{
		upper: "B",
		lower: "b",
		sound: "b",
		romanized: "b",
		exampleWord: "Balık",
		exampleMeaning: "Fish",
		examplePronounced: "bah-LUHK",
		type: "consonant",
		tip: "Like English 'b'.",
	},
	{
		upper: "C",
		lower: "c",
		sound: "j",
		romanized: "c",
		exampleWord: "Cam",
		exampleMeaning: "Glass",
		examplePronounced: "jahm",
		type: "consonant",
		tip: "Always pronounced like the 'j' in 'jam'.",
	},
	{
		upper: "Ç",
		lower: "ç",
		sound: "ch",
		romanized: "ç",
		exampleWord: "Çay",
		exampleMeaning: "Tea",
		examplePronounced: "chai",
		type: "consonant",
		tip: "Like 'ch' in 'chair'.",
	},
	{
		upper: "D",
		lower: "d",
		sound: "d",
		romanized: "d",
		exampleWord: "Deniz",
		exampleMeaning: "Sea",
		examplePronounced: "deh-NEEZ",
		type: "consonant",
		tip: "Like English 'd'.",
	},
	{
		upper: "E",
		lower: "e",
		sound: "eh",
		romanized: "e",
		exampleWord: "Ev",
		exampleMeaning: "House",
		examplePronounced: "ev",
		type: "vowel",
		tip: "Like 'e' in 'bed'.",
	},
	{
		upper: "F",
		lower: "f",
		sound: "f",
		romanized: "f",
		exampleWord: "Fil",
		exampleMeaning: "Elephant",
		examplePronounced: "feel",
		type: "consonant",
		tip: "Like English 'f'.",
	},
	{
		upper: "G",
		lower: "g",
		sound: "g",
		romanized: "g",
		exampleWord: "Güneş",
		exampleMeaning: "Sun",
		examplePronounced: "goo-NESH",
		type: "consonant",
		tip: "Always hard like the 'g' in 'go'.",
	},
	{
		upper: "Ğ",
		lower: "ğ",
		sound: "lengthens vowel",
		romanized: "ğ",
		exampleWord: "Dağ",
		exampleMeaning: "Mountain",
		examplePronounced: "dah",
		type: "consonant",
		tip: "Soft G. Usually lengthens the preceding vowel instead of making its own sound.",
	},
	{
		upper: "H",
		lower: "h",
		sound: "h",
		romanized: "h",
		exampleWord: "Hava",
		exampleMeaning: "Weather",
		examplePronounced: "HAH-vah",
		type: "consonant",
		tip: "Like English 'h'.",
	},
	{
		upper: "I",
		lower: "ı",
		sound: "uh / ɯ",
		romanized: "ı",
		exampleWord: "Işık",
		exampleMeaning: "Light",
		examplePronounced: "uh-SHUHK",
		type: "vowel",
		tip: "No English equivalent. Pronounced without rounding the lips.",
	},
	{
		upper: "İ",
		lower: "i",
		sound: "ee",
		romanized: "i",
		exampleWord: "İnsan",
		exampleMeaning: "Person",
		examplePronounced: "een-SAHN",
		type: "vowel",
		tip: "Like 'ee' in 'see'. Notice the dotted capital İ.",
	},
	{
		upper: "J",
		lower: "j",
		sound: "zh",
		romanized: "j",
		exampleWord: "Jandarma",
		exampleMeaning: "Gendarmerie",
		examplePronounced: "zhan-DAR-ma",
		type: "consonant",
		tip: "Like the 's' in 'measure'. Mostly found in loanwords.",
	},
	{
		upper: "K",
		lower: "k",
		sound: "k",
		romanized: "k",
		exampleWord: "Kitap",
		exampleMeaning: "Book",
		examplePronounced: "kee-TAP",
		type: "consonant",
		tip: "Like English 'k'.",
	},
	{
		upper: "L",
		lower: "l",
		sound: "l",
		romanized: "l",
		exampleWord: "Limon",
		exampleMeaning: "Lemon",
		examplePronounced: "lee-MON",
		type: "consonant",
		tip: "Like English 'l'.",
	},
	{
		upper: "M",
		lower: "m",
		sound: "m",
		romanized: "m",
		exampleWord: "Masa",
		exampleMeaning: "Table",
		examplePronounced: "MAH-sah",
		type: "consonant",
		tip: "Like English 'm'.",
	},
	{
		upper: "N",
		lower: "n",
		sound: "n",
		romanized: "n",
		exampleWord: "Nehir",
		exampleMeaning: "River",
		examplePronounced: "neh-HEER",
		type: "consonant",
		tip: "Like English 'n'.",
	},
	{
		upper: "O",
		lower: "o",
		sound: "o",
		romanized: "o",
		exampleWord: "Okul",
		exampleMeaning: "School",
		examplePronounced: "oh-KOOL",
		type: "vowel",
		tip: "Like 'o' in 'more', but shorter.",
	},
	{
		upper: "Ö",
		lower: "ö",
		sound: "ö",
		romanized: "ö",
		exampleWord: "Öğrenci",
		exampleMeaning: "Student",
		examplePronounced: "UR-en-jee",
		type: "vowel",
		tip: "Like the German 'ö' or the French 'eu'.",
	},
	{
		upper: "P",
		lower: "p",
		sound: "p",
		romanized: "p",
		exampleWord: "Para",
		exampleMeaning: "Money",
		examplePronounced: "PAH-rah",
		type: "consonant",
		tip: "Like English 'p'.",
	},
	{
		upper: "R",
		lower: "r",
		sound: "r",
		romanized: "r",
		exampleWord: "Renk",
		exampleMeaning: "Color",
		examplePronounced: "renk",
		type: "consonant",
		tip: "Rolled or lightly tapped with the tongue.",
	},
	{
		upper: "S",
		lower: "s",
		sound: "s",
		romanized: "s",
		exampleWord: "Su",
		exampleMeaning: "Water",
		examplePronounced: "soo",
		type: "consonant",
		tip: "Like English 's'.",
	},
	{
		upper: "Ş",
		lower: "ş",
		sound: "sh",
		romanized: "ş",
		exampleWord: "Şeker",
		exampleMeaning: "Sugar",
		examplePronounced: "SHEH-ker",
		type: "consonant",
		tip: "Like 'sh' in 'ship'.",
	},
	{
		upper: "T",
		lower: "t",
		sound: "t",
		romanized: "t",
		exampleWord: "Tren",
		exampleMeaning: "Train",
		examplePronounced: "tren",
		type: "consonant",
		tip: "Like English 't'.",
	},
	{
		upper: "U",
		lower: "u",
		sound: "oo",
		romanized: "u",
		exampleWord: "Uçak",
		exampleMeaning: "Airplane",
		examplePronounced: "oo-CHAK",
		type: "vowel",
		tip: "Like 'oo' in 'moon'.",
	},
	{
		upper: "Ü",
		lower: "ü",
		sound: "ü",
		romanized: "ü",
		exampleWord: "Üzüm",
		exampleMeaning: "Grape",
		examplePronounced: "EW-zoom",
		type: "vowel",
		tip: "Like the German 'ü' or French 'u'.",
	},
	{
		upper: "V",
		lower: "v",
		sound: "v",
		romanized: "v",
		exampleWord: "Vapur",
		exampleMeaning: "Ferry",
		examplePronounced: "vah-POOR",
		type: "consonant",
		tip: "Like English 'v'.",
	},
	{
		upper: "Y",
		lower: "y",
		sound: "y",
		romanized: "y",
		exampleWord: "Yıldız",
		exampleMeaning: "Star",
		examplePronounced: "yuhl-DUHZ",
		type: "consonant",
		tip: "Like English 'y' in 'yes'.",
	},
	{
		upper: "Z",
		lower: "z",
		sound: "z",
		romanized: "z",
		exampleWord: "Zaman",
		exampleMeaning: "Time",
		examplePronounced: "zah-MAHN",
		type: "consonant",
		tip: "Like English 'z'.",
	},
];

export const typeLabel: Record<LetterType, string> = {
	vowel: "Vowel",
	consonant: "Consonant",
	special: "Special",
};

export const typeBadgeVariant: Record<
	LetterType,
	"default" | "secondary" | "outline"
> = {
	vowel: "default",
	consonant: "secondary",
	special: "outline",
};
