export type LetterType = "vowel" | "consonant" | "special";

export interface Letter {
	upper: string;
	lower: string;
	sound: string; // IPA or approximate English
	romanized: string; // common romanization
	exampleWord: string;
	exampleMeaning: string;
	examplePronounced: string;
	type: LetterType;
	tip?: string; // mnemonic or learner tip
}

export const alphabet: Letter[] = [
	{
		upper: "А",
		lower: "а",
		sound: "a",
		romanized: "a",
		exampleWord: "Арбуз",
		exampleMeaning: "Watermelon",
		examplePronounced: "ar-BOOZ",
		type: "vowel",
		tip: "Like 'a' in 'father'",
	},
	{
		upper: "Б",
		lower: "б",
		sound: "b",
		romanized: "b",
		exampleWord: "Банан",
		exampleMeaning: "Banana",
		examplePronounced: "ba-NAN",
		type: "consonant",
		tip: "Looks like a backwards 6",
	},
	{
		upper: "В",
		lower: "в",
		sound: "v",
		romanized: "v",
		exampleWord: "Волк",
		exampleMeaning: "Wolf",
		examplePronounced: "VOLK",
		type: "consonant",
		tip: "Like English 'v'",
	},
	{
		upper: "Г",
		lower: "г",
		sound: "g",
		romanized: "g",
		exampleWord: "Город",
		exampleMeaning: "City",
		examplePronounced: "GO-rod",
		type: "consonant",
		tip: "Like English 'g' in 'go'",
	},
	{
		upper: "Д",
		lower: "д",
		sound: "d",
		romanized: "d",
		exampleWord: "Дом",
		exampleMeaning: "House",
		examplePronounced: "DOM",
		type: "consonant",
		tip: "Like English 'd'",
	},
	{
		upper: "Е",
		lower: "е",
		sound: "ye",
		romanized: "ye",
		exampleWord: "Еда",
		exampleMeaning: "Food",
		examplePronounced: "ye-DA",
		type: "vowel",
		tip: "Like 'ye' in 'yet'",
	},
	{
		upper: "Ё",
		lower: "ё",
		sound: "yo",
		romanized: "yo",
		exampleWord: "Ёжик",
		exampleMeaning: "Hedgehog",
		examplePronounced: "YO-zhik",
		type: "vowel",
		tip: "Like 'yo' in 'yore'. Often printed without dots.",
	},
	{
		upper: "Ж",
		lower: "ж",
		sound: "zh",
		romanized: "zh",
		exampleWord: "Жук",
		exampleMeaning: "Beetle",
		examplePronounced: "ZHOOK",
		type: "consonant",
		tip: "Like 's' in 'measure'. Always hard.",
	},
	{
		upper: "З",
		lower: "з",
		sound: "z",
		romanized: "z",
		exampleWord: "Зима",
		exampleMeaning: "Winter",
		examplePronounced: "zi-MA",
		type: "consonant",
		tip: "Like English 'z'",
	},
	{
		upper: "И",
		lower: "и",
		sound: "ee",
		romanized: "i",
		exampleWord: "Имя",
		exampleMeaning: "Name",
		examplePronounced: "EE-mya",
		type: "vowel",
		tip: "Like 'ee' in 'see'",
	},
	{
		upper: "Й",
		lower: "й",
		sound: "y",
		romanized: "y",
		exampleWord: "Йога",
		exampleMeaning: "Yoga",
		examplePronounced: "YO-ga",
		type: "vowel",
		tip: "Short 'y' sound. Called 'и краткое' (short и).",
	},
	{
		upper: "К",
		lower: "к",
		sound: "k",
		romanized: "k",
		exampleWord: "Кот",
		exampleMeaning: "Cat",
		examplePronounced: "KOT",
		type: "consonant",
		tip: "Like English 'k'",
	},
	{
		upper: "Л",
		lower: "л",
		sound: "l",
		romanized: "l",
		exampleWord: "Луна",
		exampleMeaning: "Moon",
		examplePronounced: "lu-NA",
		type: "consonant",
		tip: "Like English 'l'",
	},
	{
		upper: "М",
		lower: "м",
		sound: "m",
		romanized: "m",
		exampleWord: "Мама",
		exampleMeaning: "Mom",
		examplePronounced: "MA-ma",
		type: "consonant",
		tip: "Like English 'm'",
	},
	{
		upper: "Н",
		lower: "н",
		sound: "n",
		romanized: "n",
		exampleWord: "Нос",
		exampleMeaning: "Nose",
		examplePronounced: "NOS",
		type: "consonant",
		tip: "Like English 'n'",
	},
	{
		upper: "О",
		lower: "о",
		sound: "o",
		romanized: "o",
		exampleWord: "Окно",
		exampleMeaning: "Window",
		examplePronounced: "ok-NO",
		type: "vowel",
		tip: "Like 'o' in 'more' when stressed",
	},
	{
		upper: "П",
		lower: "п",
		sound: "p",
		romanized: "p",
		exampleWord: "Папа",
		exampleMeaning: "Dad",
		examplePronounced: "PA-pa",
		type: "consonant",
		tip: "Like English 'p'",
	},
	{
		upper: "Р",
		lower: "р",
		sound: "r",
		romanized: "r",
		exampleWord: "Рыба",
		exampleMeaning: "Fish",
		examplePronounced: "RY-ba",
		type: "consonant",
		tip: "Rolled 'r' — trilled with the tongue tip",
	},
	{
		upper: "С",
		lower: "с",
		sound: "s",
		romanized: "s",
		exampleWord: "Слон",
		exampleMeaning: "Elephant",
		examplePronounced: "SLON",
		type: "consonant",
		tip: "Like English 's'",
	},
	{
		upper: "Т",
		lower: "т",
		sound: "t",
		romanized: "t",
		exampleWord: "Тигр",
		exampleMeaning: "Tiger",
		examplePronounced: "TIGR",
		type: "consonant",
		tip: "Like English 't'",
	},
	{
		upper: "У",
		lower: "у",
		sound: "oo",
		romanized: "u",
		exampleWord: "Утка",
		exampleMeaning: "Duck",
		examplePronounced: "OOT-ka",
		type: "vowel",
		tip: "Like 'oo' in 'moon'",
	},
	{
		upper: "Ф",
		lower: "ф",
		sound: "f",
		romanized: "f",
		exampleWord: "Фото",
		exampleMeaning: "Photo",
		examplePronounced: "FO-to",
		type: "consonant",
		tip: "Like English 'f'",
	},
	{
		upper: "Х",
		lower: "х",
		sound: "kh",
		romanized: "kh",
		exampleWord: "Хлеб",
		exampleMeaning: "Bread",
		examplePronounced: "KHLEB",
		type: "consonant",
		tip: "Like 'ch' in Scottish 'loch'",
	},
	{
		upper: "Ц",
		lower: "ц",
		sound: "ts",
		romanized: "ts",
		exampleWord: "Цирк",
		exampleMeaning: "Circus",
		examplePronounced: "TSIRK",
		type: "consonant",
		tip: "Like 'ts' in 'cats'. Always hard.",
	},
	{
		upper: "Ч",
		lower: "ч",
		sound: "ch",
		romanized: "ch",
		exampleWord: "Чай",
		exampleMeaning: "Tea",
		examplePronounced: "CHAY",
		type: "consonant",
		tip: "Like 'ch' in 'chess'. Always soft.",
	},
	{
		upper: "Ш",
		lower: "ш",
		sound: "sh",
		romanized: "sh",
		exampleWord: "Школа",
		exampleMeaning: "School",
		examplePronounced: "SHKO-la",
		type: "consonant",
		tip: "Like 'sh' in 'ship'. Always hard.",
	},
	{
		upper: "Щ",
		lower: "щ",
		sound: "shch",
		romanized: "shch",
		exampleWord: "Щука",
		exampleMeaning: "Pike (fish)",
		examplePronounced: "SHCHOO-ka",
		type: "consonant",
		tip: "A softer, longer 'shch'. One of the hardest for learners.",
	},
	{
		upper: "Ъ",
		lower: "ъ",
		sound: "—",
		romanized: '"',
		exampleWord: "Объект",
		exampleMeaning: "Object",
		examplePronounced: "ob-YEKT",
		type: "special",
		tip: "Hard sign. Makes the consonant before it hard. No sound of its own.",
	},
	{
		upper: "Ы",
		lower: "ы",
		sound: "y/ɨ",
		romanized: "y",
		exampleWord: "Рыба",
		exampleMeaning: "Fish",
		examplePronounced: "RY-ba",
		type: "vowel",
		tip: "No English equivalent. Tongue mid-back, lips spread. One of the trickiest.",
	},
	{
		upper: "Ь",
		lower: "ь",
		sound: "—",
		romanized: "'",
		exampleWord: "Мать",
		exampleMeaning: "Mother",
		examplePronounced: "MAT'",
		type: "special",
		tip: "Soft sign. Softens the consonant before it. No sound of its own.",
	},
	{
		upper: "Э",
		lower: "э",
		sound: "eh",
		romanized: "e",
		exampleWord: "Этот",
		exampleMeaning: "This",
		examplePronounced: "EH-tot",
		type: "vowel",
		tip: "Like 'e' in 'met'",
	},
	{
		upper: "Ю",
		lower: "ю",
		sound: "yu",
		romanized: "yu",
		exampleWord: "Юг",
		exampleMeaning: "South",
		examplePronounced: "YOOG",
		type: "vowel",
		tip: "Like 'yu' in 'yule'",
	},
	{
		upper: "Я",
		lower: "я",
		sound: "ya",
		romanized: "ya",
		exampleWord: "Яблоко",
		exampleMeaning: "Apple",
		examplePronounced: "YAB-lo-ko",
		type: "vowel",
		tip: "Like 'ya' in 'yard'",
	},
];

export const stats = [
	{ label: "Letters total", value: "33" },
	{ label: "Vowels", value: "10" },
	{ label: "Consonants", value: "21" },
	{ label: "Special signs", value: "2" },
];

export const typeLabel: Record<LetterType, string> = {
	vowel: "Vowel",
	consonant: "Consonant",
	special: "Special",
};

export const typeBadgeVariant: Record<
	LetterType,
	"default" | "secondary" | "outline"
> = {
	vowel: "default",
	consonant: "secondary",
	special: "outline",
};
